# Generated by Django 4.1.7 on 2023-03-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_picture_remove_article_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_type',
        ),
    ]
